name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./front
